#!/usr/bin/env node
/**
 * Ensure root .env has all expected keys and sync client/.env for Vite.
 * Usage: node scripts/setup-env.js
 */

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.join(ROOT, ".env");
const EXAMPLE_PATH = path.join(ROOT, ".env.example");
const CLIENT_ENV_PATH = path.join(ROOT, "client/.env");

const DEFAULTS = {
  NODE_ENV: "development",
  PORT: "3000",
  APP_URL: "http://localhost:3000",
  MARKETING_SITE_URL: "http://localhost:3001",
  COOKIE_DOMAIN: "localhost",
  DB_CLIENT: "sqlite3",
  DATABASE_URL: "sqlite://./dev.sqlite3",
  COMMISSION_RATE: "0.25",
  MAX_UPLOAD_MB: "8",
  PDF_BASE_URL: "http://localhost:3000",
  EMAIL_BRAND_MARK_URL: "http://localhost:3000/brand/pholio-sender-avatar.png",
  STRIPE_SECRET_KEY: "",
  STRIPE_PUBLISHABLE_KEY: "",
  STRIPE_WEBHOOK_SECRET: "",
  STRIPE_PRICE_ID_MONTHLY: "",
  STRIPE_PRICE_ID_ANNUAL: "",
  INSTAGRAM_APP_ID: "",
  INSTAGRAM_APP_SECRET: "",
};

function parseEnv(content) {
  const map = new Map();
  const lines = content.split("\n");
  for (const line of lines) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (match) map.set(match[1], match[2]);
  }
  return map;
}

function ensureRootEnv() {
  if (!fs.existsSync(ENV_PATH)) {
    if (!fs.existsSync(EXAMPLE_PATH)) {
      console.error("Missing .env and .env.example");
      process.exit(1);
    }
    fs.copyFileSync(EXAMPLE_PATH, ENV_PATH);
    console.log("Created .env from .env.example");
  }

  const content = fs.readFileSync(ENV_PATH, "utf8");
  const existing = parseEnv(content);
  const appended = [];

  for (const [key, value] of Object.entries(DEFAULTS)) {
    if (!existing.has(key)) {
      appended.push(`${key}=${value}`);
    }
  }

  if (!existing.has("SESSION_SECRET") || existing.get("SESSION_SECRET") === "change-me") {
    const secret = crypto.randomBytes(32).toString("base64");
    if (existing.has("SESSION_SECRET")) {
      console.log("SESSION_SECRET is still 'change-me' — generate a new one manually.");
    } else {
      appended.push(`SESSION_SECRET=${secret}`);
    }
  }

  if (appended.length) {
    const block = `\n# Added by scripts/setup-env.js\n${appended.join("\n")}\n`;
    fs.appendFileSync(ENV_PATH, block);
    console.log(`Appended ${appended.length} missing key(s) to .env`);
  } else {
    console.log(".env already has all default keys");
  }
}

function syncClientEnv() {
  const content = fs.readFileSync(ENV_PATH, "utf8");
  const env = parseEnv(content);

  const firebaseKeys = [
    "FIREBASE_API_KEY",
    "FIREBASE_AUTH_DOMAIN",
    "FIREBASE_PROJECT_ID",
    "FIREBASE_STORAGE_BUCKET",
    "FIREBASE_MESSAGING_SENDER_ID",
    "FIREBASE_APP_ID",
    "FIREBASE_MEASUREMENT_ID",
  ];

  const lines = [
    "# Auto-generated by scripts/setup-env.js — do not commit",
    "# Vite reads FIREBASE_* and VITE_* from client/.env",
    "",
    `VITE_APP_URL=${env.get("APP_URL") || "http://localhost:5173"}`,
    `VITE_MARKETING_SITE_URL=${env.get("MARKETING_SITE_URL") || "http://localhost:3001"}`,
    "",
  ];

  for (const key of firebaseKeys) {
    const value = env.get(key);
    if (value) {
      lines.push(`${key}=${value}`);
      lines.push(`VITE_${key}=${value}`);
    }
  }

  fs.writeFileSync(CLIENT_ENV_PATH, `${lines.join("\n")}\n`);
  console.log(`Wrote ${CLIENT_ENV_PATH}`);
}

function report() {
  const env = parseEnv(fs.readFileSync(ENV_PATH, "utf8"));
  const required = [
    ["Core", ["NODE_ENV", "APP_URL", "SESSION_SECRET", "DB_CLIENT"]],
    ["Firebase", ["FIREBASE_API_KEY", "FIREBASE_PROJECT_ID", "FIREBASE_PRIVATE_KEY", "FIREBASE_CLIENT_EMAIL"]],
    ["Stripe (Studio+)", ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET", "STRIPE_PRICE_ID_MONTHLY", "STRIPE_PRICE_ID_ANNUAL"]],
    ["Email", ["SMTP_HOST", "SMTP_USER", "SMTP_PASS", "EMAIL_FROM"]],
    ["Storage (optional local)", ["R2_BUCKET", "R2_ACCESS_KEY_ID"]],
    ["AI (optional)", ["GROQ_API_KEY", "OPENAI_API_KEY"]],
  ];

  console.log("\nConfiguration status:");
  for (const [group, keys] of required) {
    const status = keys.map((key) => {
      const val = env.get(key);
      const ok = val && val !== '""' && val !== "change-me";
      return `${key}: ${ok ? "set" : "missing"}`;
    });
    console.log(`  ${group}: ${status.join(", ")}`);
  }
}

ensureRootEnv();
syncClientEnv();
report();
