S=/Users/lenquanhone/Projects/pholio-app/scratchpad/pitch-deck/ui-stack
export DB_CLIENT=sqlite3 DATABASE_URL=sqlite://$S/deck.sqlite3 NODE_ENV=development PORT=3100 APP_URL=http://localhost:5175
export UPLOAD_DIR=$S/uploads USE_R2=false R2_BUCKET= R2_ACCOUNT_ID= R2_ACCESS_KEY_ID= R2_SECRET_ACCESS_KEY= R2_PUBLIC_URL=
export SMTP_HOST= SMTP_PORT= SMTP_USER= SMTP_PASS= RESEND_API_KEY= STRIPE_SECRET_KEY= STRIPE_WEBHOOK_SECRET= STRIPE_PUBLISHABLE_KEY=
export OPENAI_API_KEY= GROQ_API_KEY= VOYAGE_API_KEY= COHERE_API_KEY= HIVE_API_KEY= PHOLIO_ENABLE_IMAGE_ANALYSIS=false
export MARKETING_SITE_URL=http://localhost:3001 COOKIE_DOMAIN=localhost PDF_BASE_URL=http://localhost:3100
export AUTH_PASSTHROUGH_ENABLED=1 FIREBASE_PRIVATE_KEY= APPLE_WALLET_SIGNER_KEY_PEM=
